sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=kalemena
  - secure: amWCenDVTKvv1ugD7LHKeBlWjAqc61mMtylbwD9PFfxnM7PE8J75dLWXP2DcAnTHf/yXAqXZ+w1kHmwm1TGVpnSH3jpaAP+ox8IIYMV/Yq6S02Jfn3nxyQCJSHQLy3XOR3Fh/SeEHoEGLCBzFrDDEJuyaeSGCycDElkrPIBSst87Wc7HlUQ7G8JxzHCDQXunPbDhgSEWWXvfxoZyO+1AQ4oWc/7MVnCxBw7b8xEf3TCkrnzcstx5ebJzNOcQz9MwJIKpNi51js9Vg6hwCS5MhVY66k/UntFb0zFOhcav2DqPA4i+O76DiAOEJWAQWkebc+RqNq5QgRKxbVmMQbvHvot254Q4nZfGObaulBwH7RZr/QXYVmo5EbhoQLZg3IAA7Pmi3K53Vp3NkdhP55OVu4moaVs3IcQ0fEmPq6AoZiFGA8dOUse8Kbw+CXfAxSobwxGEyx+v/QdtPrsahR/kNoF25Js5QxHxEavcCy4Vs/RllQ27NjF0TSyQge73DVAFLlyGFgPZhXR++7K7OX3F8HtWQKteiQjIdM2tIj7U/FPEH2qQ2VbvG/R2iv7/632x1jVj7J08WBSzqrnnLb69mJjdql+n+0IyPAT+xuoTaBJ8eua9BZ89R3fh6RPs/E6rgwSQCQABqb6PGu5scGzb6vsly9DkomoFkH/aGyWJziY=
  matrix:
  - IMAGE="kalemena/opencv" VERSION="latest" REPO="kalemena/docker-opencv"
before_script:
- docker pull ubuntu:18.04
- docker pull ${IMAGE}:${VERSION} || true
script:
- |
  docker build --pull --cache-from ${IMAGE}:${VERSION} \
    -t ${IMAGE}:${VERSION} \
    -f Dockerfile \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VERSION=${VERSION} .
- docker ps -a
- docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push ${IMAGE}:${VERSION}; docker push ${IMAGE}:latest
  on:
    branch: master
